name: parking_service_manager
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  
dependencies:
  auto_route: ^7.7.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  mocktail: ^0.3.0
  models:
    path: ./packages/models
  repositories:
    path: ./packages/repositories
  rxdart: ^0.27.3
  shared:
    path: ./packages/shared
  ui_kit:
    path: ./packages/ui_kit

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  linter_rules:
    path: ./packages/linter_rules

flutter:
  uses-material-design: true